concrete AlbC5RelativeGenitiveSqi of AlbC5RelativeGenitive =
  open Prelude, ParamX, ResSqi, (SN = StructuralSqiNominal) in {
  lincat Probe = {s : Str} ;
  lin
    C5R01 = {s = SN.which_IQuant.s ! Nom ! Masc ! Sg} ;
    C5R02 = {s = SN.which_IQuant.s ! Nom ! Masc ! Pl} ;
    C5R03 = {s = SN.which_IQuant.s ! Nom ! Fem ! Sg} ;
    C5R04 = {s = SN.which_IQuant.s ! Nom ! Fem ! Pl} ;
    C5R05 = {s = SN.which_IQuant.s ! Acc ! Masc ! Sg} ;
    C5R06 = {s = SN.which_IQuant.s ! Acc ! Masc ! Pl} ;
    C5R07 = {s = SN.which_IQuant.s ! Acc ! Fem ! Sg} ;
    C5R08 = {s = SN.which_IQuant.s ! Acc ! Fem ! Pl} ;
    C5R09 = {s = SN.which_IQuant.s ! Gen ! Masc ! Sg} ;
    C5R10 = {s = SN.which_IQuant.s ! Gen ! Masc ! Pl} ;
    C5R11 = {s = SN.which_IQuant.s ! Gen ! Fem ! Sg} ;
    C5R12 = {s = SN.which_IQuant.s ! Gen ! Fem ! Pl} ;
    C5R13 = {s = SN.which_IQuant.s ! Dat ! Masc ! Sg} ;
    C5R14 = {s = SN.which_IQuant.s ! Dat ! Masc ! Pl} ;
    C5R15 = {s = SN.which_IQuant.s ! Dat ! Fem ! Sg} ;
    C5R16 = {s = SN.which_IQuant.s ! Dat ! Fem ! Pl} ;
    C5R17 = {s = SN.which_IQuant.s ! Ablat ! Masc ! Sg} ;
    C5R18 = {s = SN.which_IQuant.s ! Ablat ! Masc ! Pl} ;
    C5R19 = {s = SN.which_IQuant.s ! Ablat ! Fem ! Sg} ;
    C5R20 = {s = SN.which_IQuant.s ! Ablat ! Fem ! Pl} ;
    C5R21 = {s = nyje ! Indef ! Nom ! Masc ! Sg} ;
    C5R22 = {s = nyje ! Indef ! Nom ! Masc ! Pl} ;
    C5R23 = {s = nyje ! Indef ! Nom ! Fem ! Sg} ;
    C5R24 = {s = nyje ! Indef ! Nom ! Fem ! Pl} ;
    C5R25 = {s = nyje ! Indef ! Acc ! Masc ! Sg} ;
    C5R26 = {s = nyje ! Indef ! Acc ! Masc ! Pl} ;
    C5R27 = {s = nyje ! Indef ! Acc ! Fem ! Sg} ;
    C5R28 = {s = nyje ! Indef ! Acc ! Fem ! Pl} ;
    C5R29 = {s = nyje ! Indef ! Gen ! Masc ! Sg} ;
    C5R30 = {s = nyje ! Indef ! Gen ! Masc ! Pl} ;
    C5R31 = {s = nyje ! Indef ! Gen ! Fem ! Sg} ;
    C5R32 = {s = nyje ! Indef ! Gen ! Fem ! Pl} ;
    C5R33 = {s = nyje ! Indef ! Dat ! Masc ! Sg} ;
    C5R34 = {s = nyje ! Indef ! Dat ! Masc ! Pl} ;
    C5R35 = {s = nyje ! Indef ! Dat ! Fem ! Sg} ;
    C5R36 = {s = nyje ! Indef ! Dat ! Fem ! Pl} ;
    C5R37 = {s = nyje ! Indef ! Ablat ! Masc ! Sg} ;
    C5R38 = {s = nyje ! Indef ! Ablat ! Masc ! Pl} ;
    C5R39 = {s = nyje ! Indef ! Ablat ! Fem ! Sg} ;
    C5R40 = {s = nyje ! Indef ! Ablat ! Fem ! Pl} ;
    C5R41 = {s = nyje ! Def ! Nom ! Masc ! Sg} ;
    C5R42 = {s = nyje ! Def ! Nom ! Masc ! Pl} ;
    C5R43 = {s = nyje ! Def ! Nom ! Fem ! Sg} ;
    C5R44 = {s = nyje ! Def ! Nom ! Fem ! Pl} ;
    C5R45 = {s = nyje ! Def ! Acc ! Masc ! Sg} ;
    C5R46 = {s = nyje ! Def ! Acc ! Masc ! Pl} ;
    C5R47 = {s = nyje ! Def ! Acc ! Fem ! Sg} ;
    C5R48 = {s = nyje ! Def ! Acc ! Fem ! Pl} ;
    C5R49 = {s = nyje ! Def ! Gen ! Masc ! Sg} ;
    C5R50 = {s = nyje ! Def ! Gen ! Masc ! Pl} ;
    C5R51 = {s = nyje ! Def ! Gen ! Fem ! Sg} ;
    C5R52 = {s = nyje ! Def ! Gen ! Fem ! Pl} ;
    C5R53 = {s = nyje ! Def ! Dat ! Masc ! Sg} ;
    C5R54 = {s = nyje ! Def ! Dat ! Masc ! Pl} ;
    C5R55 = {s = nyje ! Def ! Dat ! Fem ! Sg} ;
    C5R56 = {s = nyje ! Def ! Dat ! Fem ! Pl} ;
    C5R57 = {s = nyje ! Def ! Ablat ! Masc ! Sg} ;
    C5R58 = {s = nyje ! Def ! Ablat ! Masc ! Pl} ;
    C5R59 = {s = nyje ! Def ! Ablat ! Fem ! Sg} ;
    C5R60 = {s = nyje ! Def ! Ablat ! Fem ! Pl} ;
} ;
