concrete AlbC5PronounCasesSqi of AlbC5PronounCases =
  open Prelude, ParamX, ResSqi, (SN = StructuralSqiNominal) in {
  lincat Probe = {s : Str} ;
  lin
    C5P01 = {s = SN.i_Pron.s ! Nom} ;
    C5P02 = {s = SN.i_Pron.s ! Acc} ;
    C5P03 = {s = SN.i_Pron.s ! Gen} ;
    C5P04 = {s = SN.i_Pron.s ! Dat} ;
    C5P05 = {s = SN.i_Pron.s ! Ablat} ;
    C5P06 = {s = SN.we_Pron.s ! Nom} ;
    C5P07 = {s = SN.we_Pron.s ! Acc} ;
    C5P08 = {s = SN.we_Pron.s ! Gen} ;
    C5P09 = {s = SN.we_Pron.s ! Dat} ;
    C5P10 = {s = SN.we_Pron.s ! Ablat} ;
    C5P11 = {s = SN.youSg_Pron.s ! Nom} ;
    C5P12 = {s = SN.youSg_Pron.s ! Acc} ;
    C5P13 = {s = SN.youSg_Pron.s ! Gen} ;
    C5P14 = {s = SN.youSg_Pron.s ! Dat} ;
    C5P15 = {s = SN.youSg_Pron.s ! Ablat} ;
    C5P16 = {s = SN.youPl_Pron.s ! Nom} ;
    C5P17 = {s = SN.youPl_Pron.s ! Acc} ;
    C5P18 = {s = SN.youPl_Pron.s ! Gen} ;
    C5P19 = {s = SN.youPl_Pron.s ! Dat} ;
    C5P20 = {s = SN.youPl_Pron.s ! Ablat} ;
    C5P21 = {s = SN.he_Pron.s ! Nom} ;
    C5P22 = {s = SN.he_Pron.s ! Acc} ;
    C5P23 = {s = SN.he_Pron.s ! Gen} ;
    C5P24 = {s = SN.he_Pron.s ! Dat} ;
    C5P25 = {s = SN.he_Pron.s ! Ablat} ;
    C5P26 = {s = SN.she_Pron.s ! Nom} ;
    C5P27 = {s = SN.she_Pron.s ! Acc} ;
    C5P28 = {s = SN.she_Pron.s ! Gen} ;
    C5P29 = {s = SN.she_Pron.s ! Dat} ;
    C5P30 = {s = SN.she_Pron.s ! Ablat} ;
    C5P31 = {s = SN.it_Pron.s ! Nom} ;
    C5P32 = {s = SN.it_Pron.s ! Acc} ;
    C5P33 = {s = SN.it_Pron.s ! Gen} ;
    C5P34 = {s = SN.it_Pron.s ! Dat} ;
    C5P35 = {s = SN.it_Pron.s ! Ablat} ;
    C5P36 = {s = SN.that_Quant.s ! Nom ! Masc ! Sg} ;
    C5P37 = {s = SN.that_Quant.s ! Acc ! Masc ! Sg} ;
    C5P38 = {s = SN.that_Quant.s ! Gen ! Masc ! Sg} ;
    C5P39 = {s = SN.that_Quant.s ! Dat ! Masc ! Sg} ;
    C5P40 = {s = SN.that_Quant.s ! Ablat ! Masc ! Sg} ;
    C5P41 = {s = SN.that_Quant.s ! Nom ! Fem ! Sg} ;
    C5P42 = {s = SN.that_Quant.s ! Acc ! Fem ! Sg} ;
    C5P43 = {s = SN.that_Quant.s ! Gen ! Fem ! Sg} ;
    C5P44 = {s = SN.that_Quant.s ! Dat ! Fem ! Sg} ;
    C5P45 = {s = SN.that_Quant.s ! Ablat ! Fem ! Sg} ;
    C5P46 = {s = SN.this_Quant.s ! Nom ! Masc ! Sg} ;
    C5P47 = {s = SN.this_Quant.s ! Acc ! Masc ! Sg} ;
    C5P48 = {s = SN.this_Quant.s ! Gen ! Masc ! Sg} ;
    C5P49 = {s = SN.this_Quant.s ! Dat ! Masc ! Sg} ;
    C5P50 = {s = SN.this_Quant.s ! Ablat ! Masc ! Sg} ;
    C5P51 = {s = SN.this_Quant.s ! Nom ! Fem ! Sg} ;
    C5P52 = {s = SN.this_Quant.s ! Acc ! Fem ! Sg} ;
    C5P53 = {s = SN.this_Quant.s ! Gen ! Fem ! Sg} ;
    C5P54 = {s = SN.this_Quant.s ! Dat ! Fem ! Sg} ;
    C5P55 = {s = SN.this_Quant.s ! Ablat ! Fem ! Sg} ;
} ;
